version: 2
updates:
  - package-ecosystem: "bundler"
    directory: "/"
    schedule:
      interval: "daily"
      time: "04:30"
      timezone: "Europe/Stockholm"
    vendor: true
    open-pull-requests-limit: 99
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
      time: "04:30"
      timezone: "Europe/Stockholm"
