inherit_mode:
  merge:
    - Exclude

AllCops:
  DisabledByDefault: true
  SuggestExtensions: false

  Exclude:
    - 'tmp/**/*'

Style/FrozenStringLiteralComment:
  Enabled: true
Style/MutableConstant:
  Enabled: true
Layout/DotPosition:
  Enabled: true
