version: "3.9"
services:
  app:
    build:
      context: .
      args:
        - RUBY_VERSION
    ports:
      - "127.0.0.1:8080:3000"
    env_file:
      - ./default.env
    environment:
      PORT: 3000
    volumes:
      - ./storage:/app/storage
