app = "wikimum"
primary_region = "arn"

[processes]
  # Dockerfile controls this
  # https://community.fly.io/t/multiple-process-dockerfile/13639
  web = ""

[env]
  PORT = "8080"
  RACK_ENV = "production"

[[services]]
  processes = ["web"]
  internal_port = 8080
  protocol = "tcp"

  [[services.ports]]
    handlers = ["http"]
    port = 80
  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443
