app = "wikimum"

[build]
  builder = "heroku/buildpacks:20"

[processes]
  web = "/bin/sh -c 'bin/db_migrate && bin/web_start'"

[env]
  PRIMARY_REGION = "ams"
  PORT = "8080"
  RACK_ENV = "production"

[[services]]
  processes = ["web"]
  internal_port = 8080
  protocol = "tcp"

  [[services.ports]]
    handlers = ["http"]
    port = 80
  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443
