app = "wikimum"

[build]
  builder = "heroku/buildpacks:20"

[env]
  PRIMARY_REGION = "ams"
  PORT = "8080"
  RACK_ENV = "production"

[[services]]
  internal_port = 8080
  protocol = "tcp"

  [[services.ports]]
    handlers = ["http"]
    port = 80
  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443
