source 'http://rubygems.org/'
ruby '2.1.3'

gem 'sequel'
gem 'pg'
gem 'sequel_pg'
gem 'sinatra'
gem 'sinatra-contrib'
gem 'rack-flash3', require: 'rack-flash'
gem 'haml'
gem 'unicorn'
gem 'rack-ssl'
gem 'html-pipeline'
gem 'github-markdown'
gem 'github-linguist'
gem 'oauth2'
gem 'rest-client'
gem 'dotenv'
gem 'newrelic_rpm'
gem 'octokit'

group :development do
  gem 'foreman'
  gem 'racksh'
  gem 'rake'
  gem 'pry'
end
