source 'https://rubygems.org/'
ruby '2.2.3'

gem 'sequel'
gem 'pg'
gem 'sequel_pg'
gem 'sinatra'
gem 'sinatra-contrib'
gem 'rack-flash3', require: 'rack-flash'
gem 'haml'
gem 'puma'
gem 'rack-ssl'
gem 'html-pipeline'
gem 'github-markdown'
gem 'oauth2'
gem 'rest-client'
gem 'newrelic_rpm'
gem 'octokit'
gem 'addressable'
gem 'opbeat'
gem 'racksh'

group :development do
  gem 'foreman'
  gem 'rake'
  gem 'pry'
  gem 'tool', github: 'rkh/tool'
end
