# The application needs a restart after changing settings

main:
  address: "http://wiki.starkast.net/"
  secure_address: "http://wiki.starkast.net/"
  ssl_available:
  default_protocol: "http://"
  name: "Starkast Wiki"

title:
  prefix: 
  suffix: Starkast
  delimiter: '-'

permission:
  create_page_for_all_users: true

user:
  registration: true
  password_recovery: # XXX
  viewable_by_all_users: # XXX

page:
  index: Förstasidan

mail:
  registration_notify: true
  sender: null@starkast.net
