# This file is autogenerated. Instead of editing this file, please use the
# migrations feature of ActiveRecord to incrementally modify your database, and
# then regenerate this schema definition.

ActiveRecord::Schema.define(:version => 4) do

  create_table "groups", :force => true do |t|
    t.column "created_on", :timestamp
    t.column "created_by", :integer, :default => 0, :null => false
    t.column "name", :string, :limit => 35, :default => "", :null => false
    t.column "notes", :text, :default => "", :null => false
    t.column "compiled_notes", :text, :default => "", :null => false
  end

  add_index "groups", ["id"], :name => "id", :unique => true

  create_table "groups_users", :id => false, :force => true do |t|
    t.column "group_id", :integer, :default => 0, :null => false
    t.column "user_id", :integer, :default => 0, :null => false
  end

  add_index "groups_users", ["group_id", "user_id"], :name => "group_id", :unique => true

  create_table "pages", :force => true do |t|
    t.column "updated_by", :integer, :limit => 3, :default => 0, :null => false
    t.column "title_char", :string, :limit => 1, :default => "", :null => false
    t.column "title", :string, :limit => 35, :default => "", :null => false
    t.column "shorthand_title", :string, :limit => 35, :default => "", :null => false
    t.column "content", :text, :default => "", :null => false
    t.column "compiled_content", :text, :default => "", :null => false
    t.column "comment", :text, :default => "", :null => false
    t.column "compiled_comment", :text, :default => "", :null => false
    t.column "description", :text, :default => "", :null => false
    t.column "compiled_description", :text, :default => "", :null => false
    t.column "created_by", :integer, :default => 0
    t.column "created_on", :datetime, :null => false
    t.column "updated_on", :datetime, :null => false
    t.column "revision", :integer, :default => 1, :null => false
    t.column "lock_version", :integer, :default => 0, :null => false
    t.column "markup", :string, :limit => 30
  end

  create_table "permissions", :force => true do |t|
    t.column "type", :string, :limit => 20, :default => "", :null => false
    t.column "page_id", :integer, :default => 0, :null => false
    t.column "user_id", :integer, :default => 0
    t.column "group_id", :integer, :default => 0
    t.column "global", :boolean, :default => false
  end

  add_index "permissions", ["page_id", "user_id", "group_id", "global"], :name => "unique", :unique => true

  create_table "revisions", :force => true do |t|
    t.column "page_id", :integer, :default => 0, :null => false
    t.column "updated_by", :integer, :limit => 3, :default => 0, :null => false
    t.column "title_char", :string, :limit => 1, :default => "", :null => false
    t.column "title", :string, :limit => 35, :default => "", :null => false
    t.column "shorthand_title", :string, :limit => 35, :default => "", :null => false
    t.column "content", :text, :default => "", :null => false
    t.column "compiled_content", :text, :default => "", :null => false
    t.column "comment", :text, :default => "", :null => false
    t.column "compiled_comment", :text, :default => "", :null => false
    t.column "description", :text, :default => "", :null => false
    t.column "compiled_description", :text, :default => "", :null => false
    t.column "created_by", :integer, :default => 0
    t.column "created_on", :datetime, :null => false
    t.column "updated_on", :datetime, :null => false
    t.column "revision", :integer, :default => 1, :null => false
    t.column "lock_version", :integer, :default => 0, :null => false
    t.column "markup", :string, :limit => 30
  end

  add_index "revisions", ["id"], :name => "id", :unique => true

  create_table "sessions", :force => true do |t|
    t.column "sessid", :string, :limit => 32
    t.column "data", :text
    t.column "updated_at", :datetime
  end

  add_index "sessions", ["sessid"], :name => "sessid"

  create_table "users", :force => true do |t|
    t.column "type", :string, :limit => 20, :default => "", :null => false
    t.column "ip", :string, :limit => 15, :default => "", :null => false
    t.column "login", :string, :limit => 35, :default => "", :null => false
    t.column "hashed_password", :string, :limit => 40, :default => "", :null => false
    t.column "salt", :string, :limit => 40, :default => "", :null => false
    t.column "name", :string, :limit => 50, :default => "", :null => false
    t.column "admin", :boolean, :default => false, :null => false
    t.column "email", :string, :limit => 150, :default => "", :null => false
    t.column "company", :string, :limit => 35
    t.column "created_on", :datetime, :null => false
    t.column "created_by", :integer, :default => 0, :null => false
    t.column "last_login", :datetime
    t.column "notes", :text
    t.column "compiled_notes", :text
    t.column "lock_version", :integer, :default => 0
    t.column "markup", :string, :limit => 30
  end

  add_index "users", ["id"], :name => "id", :unique => true

end
