name: Help Dependabot with vendoring

on:
  push:
    branches:
      - 'dependabot/bundler/**'
    paths:
      - 'Gemfile.lock'

jobs:
  bundle-install:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false
      - uses: ruby/setup-ruby@v1

      - run: bundle install
      - name: Commit and push
        run: |
          git config --global credential.helper store
          git config --local user.email `git show -s --format='%ae'`
          git config --local user.name ${GITHUB_ACTOR}
          echo https://${{ secrets.NEKOT_BUHTIG }}:x-oauth-basic@github.com >> ~/.git-credentials
          git add .
          git commit -m "`git log --oneline --format=%B -n 1 HEAD | head -n 1` (update vendor/cache)" || true
          git push https://github.com/$GITHUB_REPOSITORY.git HEAD:${GITHUB_REF}
