name: Deploy to preview app

on:
  workflow_dispatch:

jobs:
  deploy:
    concurrency: fly-deploy-preview
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v4
      - run: |
          echo "RUBY_VERSION=$(cat .ruby-version)" >> $GITHUB_ENV
      - uses: dentarg/fly@main
        with:
          app: wikimum-preview
          build-args: "RUBY_VERSION=${{ env.RUBY_VERSION }}"
          fly-token: ${{ secrets.FLY_API_TOKEN }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
